### ISSUE TITLE
Attribute error in AstromCalibSimE2E

### ISSUE THREAD

**Issue by alphaCassi** [smonty93/MAVISIM#5]
@jcranney  I would like to inform that the lines below give the Attribute error related to **_p0_true**, **_ppx_true** and **_ppy_true**:
        _**source_p0 = SourceHack(self._p0_true + self._true_cam_samp * 0.5)
        source_ppx = SourceHack(self._ppx_true + self._true_cam_samp * 0.5)
        source_ppy = SourceHack(self._ppy_true + self._true_cam_samp * 0.5)_**_

I solved it by initialising a function, in which you calculate these parameters, in the AstromCalibSimGeneric() in __init__:
<img width="395" alt="image" src="https://github.com/smonty93/MAVISIM/assets/68812466/46e08b7e-833b-438b-917d-8fc67ac38a17">

It works like that. However, you have two functions _set_coords_square() and _set_coords_hex(). Hence, perhaps there is a better and more general way to solve this attribute issue.

Regards,
Oleksandra

**Comment by jcranney** [comment]
@alphaCassi thanks for reminding me, I have just made several improvements and bug fixes, and added unit tests for the astrometric calibration stuff. Can you please install the newest version (>=1.1.14) and see if everything works as expected? I will close this issue for now, but please reopen if anything is still broken.

**Comment by alphaCassi** [comment]
@jcranney Thank you! Now it works perfectly.  However, the new version can be installed and works only with Python version >3.8. I saw that you stated this question, therefore I only confirm it.
