### ISSUE TITLE
Problems with function: recovered_dist(self, x, y)

### ISSUE THREAD

**Issue by davide-greggio** [smonty93/MAVISIM#7]
@jcranney 
I run a simple code to check the input and the recovered distortion with astromsim. You can find the code and the input distortion map below:
[Dist_grid_ZPL_03_rot0wave5_MAVISIM.txt](https://github.com/smonty93/MAVISIM/files/13449022/Dist_grid_ZPL_03_rot0wave5_MAVISIM.txt)
```
from mavisim import astromsim
from astropy.io import ascii
import matplotlib.pyplot as plt
import numpy as np

static_distort = ascii.read(f'D:\Oleksandra\MAVIS\MSF_Distortion\Results_MSF7nm_issue2.5\\Dist_grid_ZPL_03_rot0wave5_MAVISIM.txt')
astrom_sim = astromsim.AstromCalibSimAna(static_distort,n_poly=6)

xx,yy = np.meshgrid(np.linspace(-15,15,50),np.linspace(-15,15,50))
xx = xx.flatten()
yy = yy.flatten()
rr = (xx**2+yy**2)**0.5
# use slightly smaller field because distortions arent defined beyond 30"x30" box
maxrad = 14.5
xx = xx[rr<=maxrad]
yy = yy[rr<=maxrad]

input_dist_xx, input_dist_yy = astrom_sim.input_dist(xx, yy)

plt.figure()
plt.quiver(xx,yy,input_dist_xx,input_dist_yy)
plt.title('Input RMS distortion [uas]: %2.1f' %(np.sqrt(np.std(input_dist_xx)**2 + np.std(input_dist_yy)**2)*1e6))
plt.axis('square')
plt.xlabel('X Field (arcsec)')
plt.ylabel('Y Field (arcsec)')

recovered_dist_xx,recovered_dist_yy = astrom_sim.recovered_dist(xx,yy)
            
plt.figure()
plt.quiver(xx,yy,recovered_dist_xx,recovered_dist_yy)
plt.title('Recovered RMS distortion [uas]: %2.1f' %(np.sqrt(np.std(recovered_dist_xx)**2 + np.std(recovered_dist_yy)**2)*1e6))
plt.axis('square')
plt.xlabel('X Field (arcsec)')
plt.ylabel('Y Field (arcsec)')
```
![image](https://github.com/smonty93/MAVISIM/assets/47144931/38760572-d656-4f2f-b746-56ea91b997c9)
![image](https://github.com/smonty93/MAVISIM/assets/47144931/2413b0b6-b3a9-4f83-b047-d9b4153f03ff)

The Recovered distortion that I get is quite different from the input one and I doubt that the reason is only due to the gradient method. Do you have any idea? Is there any mistake?

**Comment by davide-greggio** [comment]
I noticed that with a more center-symmetric distortion map the recovered distortion seems better. I suspect there is something related to a wrong sign or a swap between x and y. Just my guess...

**Comment by jcranney** [comment]
Thanks @davide-greggio , sorry for the late reply. If you look at the residual distortions (difference between input and recovered), the main error is tip-tilt which is indeed not recoverable in the gradient method. Once you remove the tip-tilt component, the residual looks quite high order. The residual RMS distortions can be further reduced by increasing the polynomial order. Does this follow what you expect?

I'm a bit paranoid about x/y flips etc, so if you could generate a VERY asymmetric distortion field, we could check to see if there's any x/y flips?

Here is the code to generate the figures below:
```python
from mavisim import astromsim
from astropy.io import ascii
import matplotlib.pyplot as plt; plt.ion()
import numpy as np

static_distort = ascii.read(f'/home/jcranney/Downloads/Dist_grid_ZPL_03_rot0wave5_MAVISIM.txt')
astrom_sim = astromsim.AstromCalibSimAna(static_distort,n_poly=6)

xx,yy = np.meshgrid(np.linspace(-15,15,50),np.linspace(-15,15,50),indexing="xy")
xx = xx.flatten()
yy = yy.flatten()
rr = (xx**2+yy**2)**0.5
# use slightly smaller field because distortions arent defined beyond 30"x30" box
maxrad = 14.5
xx = xx[rr<=maxrad]
yy = yy[rr<=maxrad]
plt.subplots(2,2,figsize=[10,10])

input_dist_xx, input_dist_yy = astrom_sim.input_dist(xx, yy)
rms = np.sqrt(np.std(input_dist_xx)**2 + np.std(input_dist_yy)**2)*1e6

scale_up = 20
plt.subplot(2,2,1)
plt.quiver(xx,yy,input_dist_xx,input_dist_yy,scale=1/scale_up)
plt.title(f'Input RMS distortion [uas]: {rms:2.1f}\nArrows scaled {scale_up:0.0f}x')
plt.axis('square')
plt.xlabel('X Field (arcsec)')
plt.ylabel('Y Field (arcsec)')

recovered_dist_xx,recovered_dist_yy = astrom_sim.recovered_dist(xx,yy)
rms = np.sqrt(np.std(recovered_dist_xx)**2 + np.std(recovered_dist_yy)**2)*1e6

plt.subplot(2,2,2)
plt.quiver(xx,yy,recovered_dist_xx,recovered_dist_yy,scale=1/scale_up)
plt.title(f'Recovered RMS distortion [uas]: {rms:2.1f}\nArrows scaled {scale_up:0.0f}x')
plt.axis('square')
plt.xlabel('X Field (arcsec)')
plt.ylabel('Y Field (arcsec)')

residual_dist_xx,residual_dist_yy = astrom_sim.residual_dist(xx,yy)
            
scale_up = 50
plt.subplot(2,2,3)
plt.quiver(xx,yy,residual_dist_xx,residual_dist_yy,scale=1/scale_up)
rms = np.sqrt(np.std(residual_dist_xx)**2 + np.std(residual_dist_yy)**2)*1e6
plt.title(f'Residual RMS distortion [uas]: {rms:2.1f}\nArrows scaled {scale_up:0.0f}x')
plt.axis('square')
plt.xlabel('X Field (arcsec)')
plt.ylabel('Y Field (arcsec)')

# remove tip/tilt from residual:
residual_dist_xx -= residual_dist_xx.mean()
residual_dist_yy -= residual_dist_yy.mean()
scale_up = 100
plt.subplot(2,2,4)
plt.quiver(xx,yy,residual_dist_xx,residual_dist_yy,scale=1/scale_up)
rms = np.sqrt(np.std(residual_dist_xx)**2 + np.std(residual_dist_yy)**2)*1e6
plt.title(f'Residual RMS distortion (TT removed) [uas]: {rms:2.1f}\nArrows scaled {scale_up:0.0f}x')
plt.axis('square')
plt.xlabel('X Field (arcsec)')
plt.ylabel('Y Field (arcsec)')
plt.tight_layout()
```

![github_issue_7](https://github.com/smonty93/MAVISIM/assets/22699701/96b0f151-556d-4929-b5d8-d28acc0e865b)

Increasing `n_poly=14` seems to be the upper limit before hitting numerical issues. At that point we see RMS distortions down to 70.7 uas:

![github_issue_7-b](https://github.com/smonty93/MAVISIM/assets/22699701/308da51e-db6b-4038-90b9-92446d87fe1f)

What do you think? It seems ok to me

**Comment by davide-greggio** [comment]
@jcranney The results look reasonable to me. Oleksandra will send you a couple of asymmetric maps for a second check, but I believe that you correctly identified the reason for the discrepancy.

**Comment by jcranney** [comment]
After processing the maps provided by @alphaCassi, it seems unlikely that there are any x/y flips, see processed maps below. I'll close this issue now!
![Dist_grid_ZPL_03_obtr_700rot0wave5_MAVISIM txt](https://github.com/smonty93/MAVISIM/assets/22699701/ee703e68-e394-49df-a16d-409edb285360)
![Dist_grid_ZPL_03_vtr_700rot0wave5_MAVISIM txt](https://github.com/smonty93/MAVISIM/assets/22699701/70a46f4d-7751-4faa-b26b-ee64e9dee5ce)
